name: Kubernetes Security Scan

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'k8s/**'
      - '.github/workflows/k8s-security.yml'
  push:
    branches: [ main ]
    paths:
      - 'k8s/**'

permissions:
  contents: read
  security-events: write

jobs:
  k8s-security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Kubesec
      run: |
        curl -sSfL https://github.com/controlplaneio/kubesec/releases/download/v2.11.5/kubesec_linux_amd64.tar.gz | tar -xz
        sudo mv kubesec /usr/local/bin/
        kubesec version
        
    - name: Run Kubesec on Kubernetes manifests
      run: |
        echo "Scanning Kubernetes manifests with Kubesec..."
        for file in k8s/*.yaml; do
          echo "Scanning $file"
          kubesec scan $file || true
          echo "---"
        done
        
    - name: Install Conftest
      run: |
        curl -sSfL https://github.com/open-policy-agent/conftest/releases/download/v0.50.0/conftest_0.50.0_Linux_x86_64.tar.gz | tar -xz
        sudo mv conftest /usr/local/bin/
        
    - name: Run Conftest on Kubernetes manifests
      run: |
        echo "Running Conftest policy validation..."
        conftest test k8s/ --policy policies/ --output table
        echo "---"
        echo "Conftest JSON output:"
        conftest test k8s/ --policy policies/ --output json || true
        
    - name: Generate Kubesec SARIF report
      run: |
        echo "Generating SARIF report for Kubesec results..."
        cat > kubesec-results.sarif << SARIF_EOF
        {
          "\$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema.json",
          "version": "2.1.0",
          "runs": [
            {
              "tool": {
                "driver": {
                  "name": "Kubesec",
                  "version": "2.11.5",
                  "informationUri": "https://github.com/controlplaneio/kubesec"
                }
              },
              "results": []
            }
          ]
        }
        SARIF_EOF
        
    - name: Upload Kubesec results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'kubesec-results.sarif'
        
    - name: Comment PR with Kubesec results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          let comment = '## 🔒 Kubernetes Security Scan Results\n\n';
          comment += '### Kubesec Analysis\n';
          comment += 'Kubernetes manifests have been scanned for security best practices.\n\n';
          comment += '### Conftest Policy Validation\n';
          comment += 'OPA policies have been validated against Kubernetes configurations.\n';
          comment += 'Policies checked: resource limits, security contexts, probes, service accounts.\n\n';
          comment += '✅ **Security scan completed successfully**\n';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
