name: Security Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Run Semgrep
      uses: semgrep/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
          p/dockerfile
        
    - name: Run TruffleHog OSS
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
        extra_args: --debug --only-verified
      continue-on-error: true  # Don't fail the workflow if secrets are found
        
    - name: Run Trivy filesystem scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Install Kubesec
      run: |
        curl -sSfL https://github.com/controlplaneio/kubesec/releases/download/v2.11.5/kubesec_linux_amd64.tar.gz | tar -xz
        sudo mv kubesec /usr/local/bin/
        
    - name: Run Kubesec on Kubernetes manifests
      run: |
        echo "Scanning Kubernetes manifests with Kubesec..."
        for file in k8s/*.yaml; do
          echo "Scanning $file"
          kubesec scan $file || true
          echo "---"
        done
        
    - name: Install Conftest
      run: |
        curl -sSfL https://github.com/open-policy-agent/conftest/releases/download/v0.50.0/conftest_0.50.0_Linux_x86_64.tar.gz | tar -xz
        sudo mv conftest /usr/local/bin/
        
    - name: Run Conftest policy validation
      run: |
        echo "Running Conftest policy validation..."
        conftest test k8s/ --policy policies/ --output table || true
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'